package scan

const workspaceDashboardScript = `const workspaceGraph = workspacePayload.graph||{nodes:[],edges:[]};
const serviceMap = workspacePayload.service_map||{nodes:[],edges:[]};
const endpointTraces = workspacePayload.endpoint_traces||{traces:[]};
const graphNodes=workspaceGraph.nodes||[];
const graphEdges=workspaceGraph.edges||[];
const serviceNodes=serviceMap.nodes||[];
const serviceEdges=serviceMap.edges||[];
const traces=endpointTraces.traces||[];
const serviceById=new Map(serviceNodes.map(function(n){return [n.id,n];}));
const traceById=new Map(traces.map(function(t){return [t.id,t];}));
const state={mode:"architecture",query:"",filter:"all",selected:null,endpointService:null,endpointInventoryViewport:null,isolation:false,zoom:1,panX:0,panY:0,labels:false,drag:null,dragMoved:false,positions:new Map(),viewports:new Map()};
document.getElementById("service-count").textContent=serviceNodes.length;
document.getElementById("edge-count").textContent=serviceEdges.length;
document.getElementById("trace-count").textContent=traces.length;
function escapeHtml(v){return String(v||"").replace(/[&<>"']/g,function(c){return {"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","'":"&#39;"}[c];});}
function escapeAttr(v){return escapeHtml(v);}
function shortLabel(v,max){v=String(v||"");max=max||58;return v.length>max?v.slice(0,max-3)+"...":v;}
function includesText(values){const q=state.query.toLowerCase();return !q||values.join(" ").toLowerCase().includes(q);}
function routeStatusClass(value){value=String(value||"").toLowerCase();if(value.includes("mismatch")||value.includes("risk"))return "risk";if(value.includes("unresolved")||value.includes("missing"))return "warn";return "ok";}
function serviceRole(n){const role=String(n.role||"").toLowerCase();if(role)return role;const p=String(n.project||"").toLowerCase();const k=String(n.kind||"").toLowerCase();if(k==="frontend"||p.startsWith("frontend/")||p.includes("frontend")||p.includes("playwright"))return "frontend";if(k==="backend"||p.startsWith("microservices/")||p.startsWith("services/"))return "backend";return "internal";}
function serviceDomain(n){const domain=String(n.domain||"").toLowerCase();if(domain)return domain;const text=String((n.project||"")+" "+(n.label||"")+" "+(n.service||"")).toLowerCase();if(serviceRole(n)==="frontend")return "frontend";if(text.includes("document")||text.includes("container")||text.includes("topic"))return "document";if(text.includes("cadaster")||text.includes("regulation"))return "cadaster";if(text.includes("user")||text.includes("license")||text.includes("product")||text.includes("invoice")||text.includes("shop"))return "identity";return "platform";}
function filteredServiceEdges(){return serviceEdges.filter(function(e){if(state.filter==="risk"&&!(e.mismatched||e.unresolved))return false;if(state.filter==="resolved"&&!e.resolved)return false;if(state.filter==="unresolved"&&!e.unresolved)return false;return includesText([e.from_project,e.to_project,e.direction,(e.endpoints||[]).join(" "),e.risk]);});}
function visibleServices(){const edges=filteredServiceEdges();const edgeSet=new Set();edges.forEach(function(e){edgeSet.add(e.from);edgeSet.add(e.to);});return serviceNodes.filter(function(n){const keepByMode=state.filter==="all"?(edgeSet.has(n.id)||serviceRole(n)==="frontend"||state.mode==="architecture"||state.query):edgeSet.has(n.id);return keepByMode&&includesText([n.label,n.project,n.service,n.kind,n.status,n.role,n.domain]);}).slice(0,260);}
function visibleTraces(){return traces.filter(function(t){if(state.filter==="risk"&&!(t.risk&&t.risk!=="resolved"))return false;if(state.filter==="resolved"&&t.status!=="RESOLVED")return false;if(state.filter==="unresolved"&&t.status==="RESOLVED")return false;return includesText([t.route,t.from_project,t.to_project,t.status,t.risk,(t.steps||[]).map(function(s){return s.label+" "+s.file;}).join(" ")]);}).slice(0,180);}
const diagnosticCopy={
  method_mismatch:{classification:"Likely code defect",title:"Frontend and backend use different HTTP methods",next:"Compare the client call with the available backend route and check for a stale contract."},
  indexed_backend_route_missing:{classification:"Missing scan coverage",title:"No matching route was found in the indexed backend",next:"Inspect nearby backend routes and confirm that gateway prefixes and the owning service were scanned."},
  dynamic_endpoint_unresolved:{classification:"Dynamic or statically ambiguous",title:"The endpoint is built dynamically",next:"Inspect the source expression or configure the project-specific route pattern."},
  frontend_internal_api:{classification:"Expected behavior",title:"The call targets a frontend-internal API",next:"No backend action is required unless this route should leave the frontend application."}
};
function diagnosticCode(trace){return String(trace.risk||trace.status||"information").toLowerCase();}
function diagnosticPresentation(trace){const code=diagnosticCode(trace);const known=diagnosticCopy[code];if(known)return {code:code,classification:known.classification,title:known.title,next:known.next,why:"GoreGraph classified the relationship from the indexed endpoint trace and its match status.",impact:known.classification==="Expected behavior"?"No impact is expected when the call is intentionally handled inside the frontend.":"The relationship may be incomplete, incorrectly routed, or unavailable at runtime."};const title=code.split("_").filter(Boolean).map(function(word){return word.charAt(0).toUpperCase()+word.slice(1);}).join(" ")||"Diagnostic information";return {code:code,classification:"Information",title:title,next:"Inspect the trace evidence and source locations to confirm the relationship.",why:"GoreGraph recorded this technical trace classification.",impact:"Review the evidence to determine whether the relationship affects runtime behavior."};}
function isDiagnosticTrace(t){const status=String(t.status||"").toUpperCase();const risk=String(t.risk||"").toLowerCase();if(status&&status!=="RESOLVED")return true;return risk==="frontend_internal_api"||risk==="dynamic_endpoint_unresolved"||risk==="indexed_backend_route_missing"||risk==="method_mismatch";}
function diagnosticGroupKey(t){const path=String(t.path||t.route||"").toLowerCase();if(path.startsWith("/tree/")||path.includes(" /tree/"))return "tree-prefix|"+diagnosticCode(t)+"|"+(t.to_project||"unresolved");return [diagnosticCode(t),t.to_project||"unresolved",t.method||"",t.path||t.route||""].join("|");}
function diagnosticGroupTitle(t){const presentation=diagnosticPresentation(t);const path=String(t.path||t.route||"");if(path.startsWith("/tree/")||path.includes(" /tree/"))return presentation.title+" - RDBV /tree/* -> "+(t.to_project||"unresolved");return presentation.title+" - "+(t.method||"")+" "+(t.path||t.route||"");}
function buildDiagnosticGroups(){const map=new Map();traces.filter(isDiagnosticTrace).filter(function(t){const presentation=diagnosticPresentation(t);return includesText([t.route,t.from_project,t.to_project,t.status,t.risk,presentation.classification,presentation.title,presentation.next]);}).forEach(function(t){const key=diagnosticGroupKey(t);let group=map.get(key);if(!group){group={id:"diagnostic:"+key,title:diagnosticGroupTitle(t),risk:t.risk||t.status||"information",to:t.to_project||"unresolved",presentation:diagnosticPresentation(t),routes:[],projects:new Set(),traces:[]};map.set(key,group);}group.traces.push(t);group.projects.add(t.from_project||"unknown");if(!group.routes.includes(t.route))group.routes.push(t.route);});return Array.from(map.values()).map(function(g){g.projectList=Array.from(g.projects).sort();return g;}).sort(function(a,b){if(b.traces.length!==a.traces.length)return b.traces.length-a.traces.length;return a.title.localeCompare(b.title);});}
function itemButton(id,title,meta){const selected=state.selected===id?" selected":"";return '<button class="node-row'+selected+'" data-select-id="'+escapeAttr(id)+'"><strong>'+escapeHtml(title)+'</strong><span>'+escapeHtml(meta)+'</span></button>';}
function serviceListMeta(n){const status=(n.outgoing||n.incoming) ? (n.outgoing||0)+" outgoing / "+(n.incoming||0)+" incoming" : "Scanned, no outgoing API calls detected";return status+" / "+n.project;}
function serviceBoxMeta(n){return (n.outgoing||0)+" outgoing | "+(n.incoming||0)+" incoming";}
function renderList(){let html="",count=0,title="Services";if(state.mode==="diagnostics"){const groups=buildDiagnosticGroups();count=groups.length;html=groups.map(function(g){return itemButton(g.id,g.title,g.traces.length+" endpoints / "+g.presentation.classification+" / "+g.risk+" / "+g.projectList.join(", "));}).join("");title="Diagnostics";}else if(state.mode==="architecture"){const nodes=visibleServices();count=nodes.length;html=nodes.map(function(n){return itemButton(n.id,n.label||n.project,serviceListMeta(n));}).join("");title="Architecture Services";}else if(state.mode==="endpoints"){const nodes=visibleServices();count=nodes.length;html=nodes.map(function(n){return itemButton(n.id,n.label||n.project,serviceListMeta(n));}).join("");title="Endpoint Services";}document.getElementById("list-title").textContent=title;document.getElementById("node-list").innerHTML=html||"<p class='empty'>No matching items.</p>";document.getElementById("result-note").textContent="Showing "+count+" "+title.toLowerCase()+".";document.querySelectorAll("[data-select-id]").forEach(function(el){el.addEventListener("click",function(){selectOrToggleItem(el.dataset.selectId);});});}
function setViewBox(width,height){document.getElementById("workspace-graph").setAttribute("viewBox","0 0 "+Math.max(width,900)+" "+Math.max(height,620));}
function serviceLayout(nodes,width){const left=[],right=[],middle=[];nodes.forEach(function(n){const role=serviceRole(n);if(role==="frontend")left.push(n);else if(role==="backend")right.push(n);else middle.push(n);});const lanes=[left,middle,right];const xs=[90,Math.max(540,width/2-170),Math.max(940,width-430)];const positions=new Map();let maxLen=0;lanes.forEach(function(lane,i){maxLen=Math.max(maxLen,lane.length);lane.forEach(function(n,index){positions.set(n.id,{x:xs[i],y:104+index*118,lane:i,w:360,h:78});});});return {positions:positions,height:Math.max(660,190+maxLen*118),xs:xs};}
function architectureLayout(nodes,width){const domains=["frontend","document","cadaster","identity","platform"];const labels={frontend:"Frontend clients",document:"Documents / WPO",cadaster:"Cadaster / Regulation",identity:"Identity / Commerce",platform:"Platform / Internal"};const columns=domains.map(function(domain){return nodes.filter(function(n){return serviceDomain(n)===domain;});});const usable=Math.max(width,1700)-180;const step=usable/Math.max(1,domains.length-1);const positions=new Map();let maxLen=0;columns.forEach(function(column,i){maxLen=Math.max(maxLen,column.length);column.forEach(function(n,index){positions.set(n.id,{x:90+i*step,y:126+index*118,lane:i,w:360,h:78});});});return {positions:positions,height:Math.max(780,220+maxLen*118),domains:domains,labels:labels,xs:domains.map(function(_,i){return 90+i*step;})};}
function truncateWord(word,maxChars){word=String(word||"");return word.length>maxChars?shortLabel(word,maxChars):word;}
function wrapSvgText(value,maxChars,maxLines){const words=String(value||"").split(/\s+/).filter(Boolean).map(function(word){return truncateWord(word,maxChars);});const lines=[];let line="";words.forEach(function(word){const next=line?line+" "+word:word;if(next.length>maxChars&&line){lines.push(line);line=word;}else{line=next;}});if(line)lines.push(line);if(!lines.length)lines.push("");if(lines.length>maxLines){lines.length=maxLines;lines[maxLines-1]=shortLabel(lines[maxLines-1],maxChars);}return lines;}
function svgTextBlock(cls,x,y,value,maxChars,maxLines,lineHeight){return wrapSvgText(value,maxChars,maxLines).map(function(line,i){return '<text class="'+cls+'" x="'+x+'" y="'+(y+i*lineHeight)+'">'+escapeHtml(line)+'</text>';}).join("");}
function boxNode(cls,id,x,y,w,h,title,meta,selected,dim){const titleCls=cls.includes("trace")?"trace-title":cls.includes("raw")?"raw-title":"service-title";const metaCls=cls.includes("trace")?"trace-meta":cls.includes("raw")?"raw-meta":"service-meta";let html='<g class="'+cls+(selected?' selected':'')+(dim?' dim':'')+'" data-select-id="'+escapeAttr(id)+'" data-focus-id="'+escapeAttr(id)+'"><title>'+escapeHtml(title+" / "+meta)+'</title><rect x="'+x+'" y="'+y+'" width="'+w+'" height="'+h+'"></rect>';html+=svgTextBlock(titleCls,x+14,y+24,title,Math.max(18,Math.floor((w-28)/8)),2,16);html+=svgTextBlock(metaCls,x+14,y+h-26,meta,Math.max(18,Math.floor((w-28)/7)),1,14);html+='</g>';return html;}
function curvedPath(a,b){const ax=a.x+a.w,ay=a.y+a.h/2,bx=b.x,by=b.y+b.h/2,mid=(ax+bx)/2;return "M"+ax+" "+ay+" C"+mid+" "+ay+" "+mid+" "+by+" "+bx+" "+by;}
function renderServiceMap(){const svg=document.getElementById("workspace-graph");const layer=document.getElementById("graph-layer");const width=svg.clientWidth||1200;const allNodes=visibleServices();const focused=state.selected ? serviceFocus(state.selected):null;const nodes=focused?allNodes.filter(function(n){return focused.has(n.id);}):allNodes;const nodeIds=new Set(nodes.map(function(n){return n.id;}));const layout=serviceLayout(nodes,width);state.positions=layout.positions;setViewBox(width,layout.height);let body='<rect x="0" y="0" width="'+Math.max(width,1100)+'" height="'+layout.height+'" fill="transparent"></rect><text class="lane-title" x="90" y="42">Focused Service View</text><text class="raw-meta" x="90" y="66">Select a service to isolate incoming and outgoing relationships. Select it again to clear.</text>';["Frontend clients","Internal services","Backend services"].forEach(function(label,i){body+='<text class="domain-title" x="'+layout.xs[i]+'" y="94">'+label+'</text>';});filteredServiceEdges().forEach(function(e){if(!nodeIds.has(e.from)||!nodeIds.has(e.to))return;const a=layout.positions.get(e.from),c=layout.positions.get(e.to);if(!a||!c)return;const isFocused=state.selected&&(e.from===state.selected||e.to===state.selected);body+='<path class="edge '+routeStatusClass(e.risk)+(isFocused?' focused':'')+'" marker-end="url(#'+(isFocused?'arrow-focus':'arrow')+')" d="'+curvedPath(a,c)+'"></path>';if(isFocused&&state.labels){body+='<text class="edge-label" x="'+((a.x+c.x)/2+80)+'" y="'+((a.y+c.y)/2+34)+'">'+escapeHtml(e.total+" relation"+(e.total===1?"":"s"))+'</text>';}});nodes.forEach(function(n){const p=layout.positions.get(n.id);body+=boxNode("service-node",n.id,p.x,p.y,p.w,p.h,n.label||n.project,serviceBoxMeta(n),state.selected===n.id,false);});layer.innerHTML=body;wireGraphSelection();applyTransform();if(state.selected)showServiceDetails(state.selected,false);}
function renderArchitectureMap(){const svg=document.getElementById("workspace-graph");const layer=document.getElementById("graph-layer");const width=svg.clientWidth||1400;const allNodes=visibleServices();const focused=state.selected?serviceFocus(state.selected):null;const nodes=state.isolation?allNodes.filter(function(n){return focused&&focused.has(n.id);}):allNodes;const nodeIds=new Set(nodes.map(function(n){return n.id;}));const layout=architectureLayout(nodes,width);state.positions=layout.positions;setViewBox(width,layout.height);let body='<rect x="0" y="0" width="'+Math.max(width,1700)+'" height="'+layout.height+'" fill="transparent"></rect><text class="lane-title" x="90" y="42">Architecture Map</text>';layout.domains.forEach(function(domain,i){body+='<text class="domain-title" x="'+layout.xs[i]+'" y="84">'+escapeHtml(layout.labels[domain])+'</text>';});filteredServiceEdges().forEach(function(e){if(!nodeIds.has(e.from)||!nodeIds.has(e.to))return;const a=layout.positions.get(e.from),c=layout.positions.get(e.to);if(!a||!c)return;const isFocused=state.selected&&(e.from===state.selected||e.to===state.selected);body+='<path class="edge '+routeStatusClass(e.risk)+(isFocused?' focused':'')+'" marker-end="url(#'+(isFocused?'arrow-focus':'arrow')+')" d="'+curvedPath(a,c)+'"></path>';if(isFocused&&state.labels){body+='<text class="edge-label" x="'+((a.x+c.x)/2+100)+'" y="'+((a.y+c.y)/2+32)+'">'+escapeHtml(e.total+" relation"+(e.total===1?"":"s"))+'</text>';}});nodes.forEach(function(n){const p=layout.positions.get(n.id);if(!p)return;const dim=focused&&!focused.has(n.id);body+=boxNode("service-node",n.id,p.x,p.y,p.w,p.h,n.label||n.project,serviceBoxMeta(n),state.selected===n.id,dim);});layer.innerHTML=body;wireGraphSelection();applyTransform();if(state.selected)showServiceDetails(state.selected,false);}
function serviceFocus(id){const ids=new Set([id]);serviceEdges.forEach(function(e){if(e.from===id)ids.add(e.to);if(e.to===id)ids.add(e.from);});return ids;}
function serviceIdForProject(project){const node=serviceNodes.find(function(n){return n.project===project;});return node?node.id:null;}
function sourceHref(project,file,line){if(!project||!file||!workspaceGraph.root)return "";let path=workspaceGraph.root.replace(/\/$/,"")+"/"+project.replace(/^\/+/,"")+"/"+file.replace(/^\/+/,"");return "file://"+path.split("/").map(function(part,i){return i===0?"":encodeURIComponent(part);}).join("/")+(line?"#L"+line:"");}
function fileLink(project,file,line){if(!file)return "";const label=file+(line?":"+line:"");const href=sourceHref(project,file,line);return href?'<a class="source-link" href="'+escapeAttr(href)+'">'+escapeHtml(label)+'</a>':escapeHtml(label);}
function diagnosticGroupByID(id){return buildDiagnosticGroups().find(function(g){return g.id===id;});}
function renderDiagnostics(){const svg=document.getElementById("workspace-graph");const layer=document.getElementById("graph-layer");const width=Math.max(svg.clientWidth||1200,1180);const groups=buildDiagnosticGroups();state.positions=new Map();const rowH=118,top=124,x=70,w=Math.min(980,width-140),h=84;const height=Math.max(720,top+Math.max(groups.length,1)*rowH+90);setViewBox(width,height);let body='<rect x="0" y="0" width="'+Math.max(width,1180)+'" height="'+height+'" fill="transparent"></rect><text class="lane-title" x="70" y="42">Diagnostic workbench</text><text class="raw-meta" x="70" y="66">Diagnostics explain relationships GoreGraph could not safely confirm, including expected frontend-internal calls.</text><text class="domain-title" x="70" y="104">Diagnostic group</text>';if(!groups.length){body+='<text class="empty" x="70" y="150">No diagnostics for the current search/filter.</text>';}groups.forEach(function(g,i){const y=top+i*rowH;state.positions.set(g.id,{x:x,y:y,w:w,h:h});const selected=state.selected===g.id;body+='<g class="issue-card'+(selected?' selected':'')+'" data-select-id="'+escapeAttr(g.id)+'" data-focus-id="'+escapeAttr(g.id)+'"><title>'+escapeHtml(g.title)+'</title><rect x="'+x+'" y="'+y+'" width="'+w+'" height="'+h+'"></rect>';body+=svgTextBlock("issue-title",x+16,y+26,g.title,Math.floor((w-32)/8),2,16);body+=svgTextBlock("issue-meta",x+16,y+h-26,g.traces.length+" endpoints | "+g.presentation.classification+" | "+g.risk+" | "+g.projectList.join(", "),Math.floor((w-32)/7),1,14);body+='</g>';});layer.innerHTML=body;wireGraphSelection();applyTransform();if(state.selected&&String(state.selected).startsWith("diagnostic:"))showDiagnosticDetails(state.selected);}
function renderEndpointTrace(trace){const svg=document.getElementById("workspace-graph");const layer=document.getElementById("graph-layer");const width=svg.clientWidth||1100;state.positions=new Map();setViewBox(width,760);let body='<rect x="0" y="0" width="'+Math.max(width,900)+'" height="760" fill="transparent"></rect>';const steps=trace.steps||[];const gap=330;steps.forEach(function(step,i){const x=70+i*gap,y=170;const p={x:x,y:y,w:286,h:98};state.positions.set(step.id,p);body+=boxNode("trace-step trace-card "+escapeAttr(step.kind)+(state.focusStep===step.id?' focused':''),step.id,x,y,p.w,p.h,step.label,step.kind+(step.file?" / "+step.file:""),false,false);if(i+1<steps.length){const x1=x+p.w,y1=y+p.h/2,x2=70+(i+1)*gap,y2=y+p.h/2;body+='<path class="edge focused" marker-end="url(#arrow-focus)" d="M'+x1+' '+y1+' L'+x2+' '+y2+'"></path>';}});body+='<text class="lane-title" x="70" y="95">Implementation trace</text><text class="trace-title" x="70" y="122">'+escapeHtml(trace.route)+'</text><text class="trace-meta" x="70" y="144">'+escapeHtml((trace.from_project||"unknown")+" -> "+(trace.to_project||"unresolved"))+'</text>';layer.innerHTML=body;wireGraphSelection();applyTransform();showTraceDetails(trace.id,false);}
function endpointRowsForService(serviceId){const node=serviceById.get(serviceId)||visibleServices()[0];if(!node)return {service:null,rows:[]};const project=node.project;const rows=[];visibleTraces().forEach(function(t){if(t.from_project===project||t.to_project===project){rows.push({id:t.id,from:t.from_project||"unknown",route:t.route||[t.method,t.path].filter(Boolean).join(" "),to:t.to_project||"unresolved",status:t.status||"UNKNOWN",risk:t.risk||"",kind:"endpoint_trace"});}});filteredServiceEdges().forEach(function(e){if(e.from===node.id||e.to===node.id){(e.endpoints&&e.endpoints.length?e.endpoints:["service dependency"]).forEach(function(endpoint,index){rows.push({id:e.id+":path:"+index,from:e.from_project||"unknown",route:endpoint,to:e.to_project||"unknown",status:e.risk||"relationship",risk:e.risk||"",kind:"service_relation"});});}});const seen=new Set();return {service:node,rows:rows.filter(function(row){const key=row.from+"|"+row.route+"|"+row.to+"|"+row.kind;if(seen.has(key))return false;seen.add(key);return true;}).slice(0,120)};}
function renderEndpointInventory(){const svg=document.getElementById("workspace-graph");const layer=document.getElementById("graph-layer");const width=Math.max(svg.clientWidth||1200,1220);const selectedService=state.endpointService&&serviceById.has(state.endpointService)?state.endpointService:null;const model=endpointRowsForService(selectedService);if(model.service)state.endpointService=model.service.id;state.positions=new Map();const rowH=112,top=132,leftX=70,midX=430,rightX=860,cardW=300,cardH=72;const height=Math.max(720,top+Math.max(model.rows.length,1)*rowH+90);setViewBox(width,height);let body='<rect x="0" y="0" width="'+Math.max(width,1280)+'" height="'+height+'" fill="transparent"></rect><text class="lane-title" x="70" y="42">Endpoint inventory</text><text class="raw-meta" x="70" y="66">Select a service to inspect its endpoint relationships, then select an endpoint to follow its implementation trace.</text><text class="domain-title" x="'+leftX+'" y="106">Caller</text><text class="domain-title" x="'+midX+'" y="106">Endpoint</text><text class="domain-title" x="'+rightX+'" y="106">Provider</text>';
if(!model.service){layer.innerHTML=body+'<text class="empty" x="70" y="160">No service selected or available.</text>';applyTransform();return;}
if(!model.rows.length){body+='<text class="empty" x="70" y="160">No endpoints found for '+escapeHtml(model.service.label||model.service.project)+'.</text>';}
model.rows.forEach(function(row,i){const y=top+i*rowH;const fromId=serviceIdForProject(row.from)||row.id+":from",routeId=row.id,toId=serviceIdForProject(row.to)||row.id+":to";const selected=state.selected===row.id;const pFrom={x:leftX,y:y,w:cardW,h:cardH},pRoute={x:midX,y:y,w:cardW+80,h:cardH},pTo={x:rightX,y:y,w:cardW,h:cardH};state.positions.set(row.id,pRoute);state.positions.set(fromId,pFrom);state.positions.set(toId,pTo);body+=boxNode("raw-node path-card",fromId,pFrom.x,pFrom.y,pFrom.w,pFrom.h,row.from,row.kind,false,false);body+=boxNode("raw-node path-card",routeId,pRoute.x,pRoute.y,pRoute.w,pRoute.h,row.route,row.status+(row.risk?" / "+row.risk:""),selected,false);body+=boxNode("raw-node path-card",toId,pTo.x,pTo.y,pTo.w,pTo.h,row.to,row.kind,false,false);body+='<path class="edge focused" marker-end="url(#arrow-focus)" d="M'+(pFrom.x+pFrom.w)+' '+(y+cardH/2)+' L'+pRoute.x+' '+(y+cardH/2)+'"></path>';body+='<path class="edge focused" marker-end="url(#arrow-focus)" d="M'+(pRoute.x+pRoute.w)+' '+(y+cardH/2)+' L'+pTo.x+' '+(y+cardH/2)+'"></path>';});
layer.innerHTML=body;wireGraphSelection();applyTransform();showEndpointInventoryDetails(model.service,model.rows);}
function renderEndpoints(){const selectedTrace=state.selected&&traceById.get(state.selected);if(selectedTrace){renderEndpointTrace(selectedTrace);return;}renderEndpointInventory();}
function renderCanvas(){if(state.mode==="architecture")renderArchitectureMap();else if(state.mode==="endpoints")renderEndpoints();else renderDiagnostics();}
function applyTransform(){document.getElementById("graph-layer").setAttribute("transform","translate("+state.panX+" "+state.panY+") scale("+state.zoom+")");document.getElementById("zoom-readout").textContent=Math.round(state.zoom*100)+"%";}
function zoomBy(delta){state.zoom=Math.max(.35,Math.min(3,state.zoom*delta));applyTransform();}
function panBy(dx,dy){state.panX+=dx;state.panY+=dy;applyTransform();}
function resetView(){state.zoom=1;state.panX=0;state.panY=0;applyTransform();}
function saveViewport(){state.viewports.set(state.mode,{zoom:state.zoom,panX:state.panX,panY:state.panY});}
function restoreViewport(mode){const viewport=state.viewports.get(mode)||{zoom:1,panX:0,panY:0};state.zoom=viewport.zoom;state.panX=viewport.panX;state.panY=viewport.panY;}
function saveEndpointInventoryViewport(){state.endpointInventoryViewport={zoom:state.zoom,panX:state.panX,panY:state.panY};}
function restoreEndpointInventoryViewport(){const viewport=state.endpointInventoryViewport;if(!viewport)return;state.zoom=viewport.zoom;state.panX=viewport.panX;state.panY=viewport.panY;}
function centerOnPosition(id){const p=state.positions.get(id);if(!p)return;const svg=document.getElementById("workspace-graph");const width=svg.clientWidth||1100,height=svg.clientHeight||720;state.panX=(width/2-(p.x+p.w/2))*state.zoom;state.panY=(height/2-(p.y+p.h/2))*state.zoom;applyTransform();}
function focusGraphItem(id){if(!id)return;centerOnPosition(id);}
function focusTraceStep(id){state.focusStep=id;renderCanvas();centerOnPosition(id);}
function wireGraphSelection(){document.querySelectorAll("#graph-layer [data-select-id]").forEach(function(el){el.addEventListener("pointerdown",function(e){e.stopPropagation();});el.addEventListener("click",function(e){e.preventDefault();e.stopPropagation();if(state.dragMoved)return;selectOrToggleItem(el.dataset.selectId);});});}
function detailField(label,value){return value?'<div class="detail-item"><strong>'+escapeHtml(label)+'</strong><small>'+escapeHtml(value)+'</small></div>':"";}
function badges(edge){return '<span class="badge ok">'+(edge.resolved||0)+' resolved</span><span class="badge risk">'+(edge.mismatched||0)+' mismatch</span><span class="badge warn">'+(edge.unresolved||0)+' unresolved</span>';}
function edgeRows(edges,title){let html='<div class="relation-section"><h3>'+escapeHtml(title)+'</h3>';if(!edges.length)return html+'<p class="empty">None.</p></div>';edges.forEach(function(e){const other=title==="Outgoing"?serviceById.get(e.to):serviceById.get(e.from);const examples=(e.problems&&e.problems.length?e.problems:e.endpoints||[]).slice(0,3).join(" | ");html+='<button class="relation-row" data-select-id="'+escapeAttr(other?other.id:"")+'"><strong>'+escapeHtml(e.direction)+'</strong><span>'+escapeHtml(examples)+'</span>'+badges(e)+'</button>';});return html+'</div>';}
function showServiceDetails(id,select){if(select)state.selected=id;const node=serviceById.get(id);if(!node)return;const incoming=serviceEdges.filter(function(e){return e.to===id;});const outgoing=serviceEdges.filter(function(e){return e.from===id;});let html='<h1>'+escapeHtml(node.label||node.project)+'</h1><div class="detail-list">'+detailField("Project",node.project)+detailField("Kind",node.kind)+detailField("Service",node.service)+detailField("Status",node.status)+'</div>';html+=edgeRows(outgoing,"Outgoing")+edgeRows(incoming,"Incoming");document.getElementById("details").innerHTML=html;document.querySelectorAll(".relation-row[data-select-id]").forEach(function(el){el.addEventListener("click",function(){if(el.dataset.selectId)selectItem(el.dataset.selectId);});});}
function showTraceDetails(id,select){if(select)state.selected=id;const trace=traceById.get(id);if(!trace)return;let html='<button class="relation-row" id="back-to-endpoint-inventory"><strong>Back to endpoint inventory</strong></button><h1>'+escapeHtml(trace.route)+'</h1><div class="detail-list">'+detailField("Direction",(trace.from_project||"unknown")+" -> "+(trace.to_project||"unresolved"))+detailField("Status",trace.status)+detailField("Risk",trace.risk)+'</div><div class="relation-section"><h3>Implementation trace</h3>';(trace.steps||[]).forEach(function(step,i){const source=step.file?fileLink(step.project,step.file,step.line):"";html+='<button class="relation-row'+(state.focusStep===step.id?' selected':'')+'" data-step-id="'+escapeAttr(step.id)+'"><strong>'+escapeHtml((i+1)+". "+step.label)+'</strong><span>'+escapeHtml(step.kind)+(source?" / "+source:"")+'</span></button>';});html+='</div>';document.getElementById("details").innerHTML=html;document.getElementById("back-to-endpoint-inventory").addEventListener("click",returnToEndpointInventory);document.querySelectorAll("[data-step-id]").forEach(function(el){el.addEventListener("click",function(){focusTraceStep(el.dataset.stepId);});});}
function showEndpointInventoryDetails(service,rows){let html='<h1>'+escapeHtml(service.label||service.project)+'</h1><div class="detail-list">'+detailField("Project",service.project)+detailField("View","Endpoint inventory for the selected service.")+'</div><div class="relation-section"><h3>Endpoint inventory</h3>';if(!rows.length)html+='<p class="empty">No endpoints found.</p>';rows.forEach(function(row){html+='<button class="relation-row" data-endpoint-id="'+escapeAttr(row.id)+'"><strong>'+escapeHtml(row.route)+'</strong><span>'+escapeHtml(row.from+" -> "+row.to+" / "+row.status)+'</span></button>';});html+='</div>';document.getElementById("details").innerHTML=html;document.querySelectorAll("[data-endpoint-id]").forEach(function(el){el.addEventListener("click",function(){selectItem(el.dataset.endpointId);});});}
function showDiagnosticDetails(id){const group=diagnosticGroupByID(id);if(!group)return;const presentation=group.presentation;let html='<h1>'+escapeHtml(group.title)+'</h1><h3>How was this determined?</h3><div class="detail-list">'+detailField("Classification",presentation.classification)+detailField("Why GoreGraph shows this",presentation.why)+detailField("Possible impact",presentation.impact)+detailField("Evidence",group.traces.length+" endpoint trace(s); technical code: "+group.risk)+detailField("What to check next",presentation.next)+detailField("Likely owner",group.to)+detailField("Affected projects",group.projectList.join(", "))+'</div><div class="relation-section"><h3>Evidence</h3>';group.traces.forEach(function(trace){const firstSource=(trace.steps||[]).find(function(step){return step.file;});const source=firstSource?fileLink(firstSource.project,firstSource.file,firstSource.line):"";html+='<button class="relation-row" data-trace-id="'+escapeAttr(trace.id)+'"><strong>'+escapeHtml(trace.route)+'</strong><span>'+escapeHtml((trace.from_project||"unknown")+" -> "+(trace.to_project||"unresolved")+" / "+(trace.status||"UNKNOWN")+" / "+(trace.risk||""))+(source?" / "+source:"")+'</span></button>';});html+='</div>';document.getElementById("details").innerHTML=html;document.querySelectorAll("[data-trace-id]").forEach(function(el){el.addEventListener("click",function(){setMode("endpoints");selectItem(el.dataset.traceId);});});}
function setArchitectureIsolation(enabled){if(enabled&&!state.selected)return;state.isolation=enabled;document.getElementById("isolate-neighborhood").hidden=enabled||!state.selected;document.getElementById("show-full-architecture").hidden=!enabled;renderCanvas();}
function clearSelection(){state.selected=null;state.focusStep=null;state.isolation=false;document.getElementById("isolate-neighborhood").hidden=true;document.getElementById("show-full-architecture").hidden=true;document.getElementById("details").innerHTML='<p class="empty">Select a service or endpoint to inspect directed relationships.</p>';renderList();renderCanvas();}
function returnToEndpointInventory(){if(!traceById.has(state.selected))return;state.selected=state.endpointService;state.focusStep=null;restoreEndpointInventoryViewport();renderList();renderCanvas();}
function selectOrToggleItem(id){if(state.selected===id){clearSelection();return;}selectItem(id);}
function selectItem(id){state.focusStep=null;if(state.mode==="endpoints"){if(serviceById.has(id)){state.endpointService=id;state.selected=id;}else if(traceById.has(id)){saveEndpointInventoryViewport();state.selected=id;}else{return;}}else{state.selected=id;}if(state.mode==="architecture"){state.isolation=false;document.getElementById("isolate-neighborhood").hidden=false;document.getElementById("show-full-architecture").hidden=true;}renderList();renderCanvas();if(state.mode==="diagnostics")showDiagnosticDetails(id);else if(state.mode==="architecture")showServiceDetails(id,false);}
function setMode(mode){saveViewport();state.mode=mode;restoreViewport(mode);state.selected=null;if(mode==="endpoints")restoreEndpointInventoryViewport();else state.endpointService=null;state.isolation=false;state.filter="all";document.getElementById("isolate-neighborhood").hidden=true;document.getElementById("show-full-architecture").hidden=true;document.querySelectorAll("[data-view-mode]").forEach(function(btn){btn.classList.toggle("active",btn.dataset.viewMode===mode);});document.querySelectorAll("[data-kind-filter]").forEach(function(btn){btn.classList.toggle("active",btn.dataset.kindFilter==="all");});document.getElementById("mode-help").textContent=mode==="architecture"?"See how projects and services communicate across the workspace. Select a service to highlight direct incoming and outgoing relationships without changing the layout.":mode==="endpoints"?"Find an endpoint, inspect its consumers, and follow its implementation trace.":"Review relationships GoreGraph could not safely confirm and learn what to check next.";renderList();renderCanvas();}
document.getElementById("workspace-search").addEventListener("input",function(e){state.query=e.target.value;state.selected=null;state.isolation=false;document.getElementById("isolate-neighborhood").hidden=true;document.getElementById("show-full-architecture").hidden=true;renderList();renderCanvas();});
document.querySelectorAll("[data-view-mode]").forEach(function(btn){btn.addEventListener("click",function(){setMode(btn.dataset.viewMode);});});
document.querySelectorAll("[data-kind-filter]").forEach(function(btn){btn.addEventListener("click",function(){state.filter=btn.dataset.kindFilter;state.selected=null;state.isolation=false;document.getElementById("isolate-neighborhood").hidden=true;document.getElementById("show-full-architecture").hidden=true;document.querySelectorAll("[data-kind-filter]").forEach(function(b){b.classList.toggle("active",b===btn);});renderList();renderCanvas();});});
document.getElementById("zoom-in").addEventListener("click",function(){zoomBy(1.2);});
document.getElementById("zoom-out").addEventListener("click",function(){zoomBy(.84);});
document.getElementById("reset-view").addEventListener("click",resetView);
document.getElementById("clear-selection").addEventListener("click",clearSelection);
document.getElementById("isolate-neighborhood").addEventListener("click",function(){setArchitectureIsolation(true);});
document.getElementById("show-full-architecture").addEventListener("click",function(){setArchitectureIsolation(false);});
document.addEventListener("keydown",function(e){if(e.key==="Escape")clearSelection();});
document.getElementById("fit-button").addEventListener("click",function(){state.query="";state.selected=null;state.isolation=false;document.getElementById("isolate-neighborhood").hidden=true;document.getElementById("show-full-architecture").hidden=true;document.getElementById("workspace-search").value="";resetView();renderList();renderCanvas();});
document.getElementById("toggle-labels").addEventListener("click",function(){state.labels=!state.labels;this.classList.toggle("active",state.labels);renderCanvas();});
document.getElementById("workspace-graph").addEventListener("wheel",function(e){e.preventDefault();zoomBy(e.deltaY<0?1.08:.92);},{passive:false});
document.getElementById("workspace-graph").addEventListener("pointerdown",function(e){e.preventDefault();state.drag={x:e.clientX,y:e.clientY};state.dragMoved=false;this.setPointerCapture(e.pointerId);});
document.getElementById("workspace-graph").addEventListener("pointermove",function(e){if(!state.drag)return;const dx=e.clientX-state.drag.x,dy=e.clientY-state.drag.y;if(Math.abs(dx)+Math.abs(dy)>2)state.dragMoved=true;panBy(dx,dy);state.drag={x:e.clientX,y:e.clientY};});
document.getElementById("workspace-graph").addEventListener("pointerup",function(){state.drag=null;setTimeout(function(){state.dragMoved=false;},0);});
window.addEventListener("resize",renderCanvas);
renderList();renderCanvas();`
