package scan

const workspaceDashboardStyles = `:root{color-scheme:light;--color-background:#f3f6f7;--color-surface:#fff;--color-canvas:#eef4f6;--color-border:#d3dde4;--color-text:#17212b;--color-muted:#5f6f7e;--color-accent:#0b6b79;--color-focus:#0b6b79;--color-success:#287a4b;--color-warning:#a56a00;--color-danger:#a33131;font-family:Avenir Next,Segoe UI,Helvetica,Arial,sans-serif}
*{box-sizing:border-box}body{margin:0;background:var(--color-background);color:var(--color-text)}body,.shell,main,svg{user-select:none}input,.details,.node-row,.relation-row{user-select:text}button,input{font:inherit}.shell{display:grid;grid-template-columns:minmax(320px,380px) minmax(560px,1fr) minmax(320px,420px);grid-template-areas:"side main details";min-height:100vh}.side,.details{background:var(--color-surface);padding:20px;overflow:auto}.side{grid-area:side;border-right:1px solid var(--color-border)}main{grid-area:main}.details{grid-area:details;border-left:1px solid var(--color-border);font-size:15px}
h1{font-size:20px;line-height:1.2;margin:0 0 14px}.details h1{font-size:24px;line-height:1.14;overflow-wrap:anywhere}h2{font-size:12px;line-height:1.2;margin:18px 0 8px;color:var(--color-muted);text-transform:uppercase}.summary{display:grid;grid-template-columns:1fr 1fr 1fr;gap:8px;margin:12px 0 16px}.metric{border:1px solid var(--color-border);border-radius:6px;padding:9px}.metric strong{display:block;font-size:20px}.metric span{font-size:12px;color:var(--color-muted)}
input{width:100%;height:40px;border:1px solid var(--color-border);border-radius:6px;padding:0 11px;background:#fff;color:var(--color-text)}.filters,.modes,.canvas-tools{display:flex;flex-wrap:wrap;gap:7px}.filters button,.modes button,.canvas-tools button{height:32px;border:1px solid var(--color-border);border-radius:6px;background:#fff;color:var(--color-text);padding:0 10px;cursor:pointer}.filters button.active,.modes button.active,.canvas-tools button.active{background:var(--color-accent);border-color:var(--color-accent);color:#fff}
.endpoint-filters{border-top:1px solid var(--color-border);margin-top:16px;padding-top:2px}.endpoint-filters[hidden]{display:none}.endpoint-filters select{width:100%;min-height:72px;border:1px solid var(--color-border);border-radius:6px;background:#fff;color:var(--color-text);padding:5px}.filter-label{display:block;color:var(--color-muted);font-size:12px;font-weight:700;margin:10px 0 5px}.endpoint-filters>button{min-height:36px;border:1px solid var(--color-border);border-radius:6px;background:#fff;padding:0 10px}.endpoint-filter-summary{font-size:12px;color:var(--color-muted);line-height:1.4;margin:8px 0 0}
.item-list{display:grid;gap:7px;margin-top:12px}.node-row{width:100%;border:1px solid var(--color-border);border-radius:6px;background:#fff;text-align:left;padding:10px;cursor:pointer}.node-row strong{display:block;font-size:13px;line-height:1.25;overflow-wrap:anywhere}.node-row span{display:block;font-size:12px;color:var(--color-muted);margin-top:4px;overflow-wrap:anywhere}.node-row.selected{border-color:var(--color-accent);box-shadow:inset 3px 0 0 var(--color-accent)}
.result-note,.help{font-size:13px;color:var(--color-muted);line-height:1.45;margin:10px 0 0}.glossary{border-top:1px solid var(--color-border);margin-top:16px;padding-top:12px}.glossary p{font-size:12px;line-height:1.35;color:var(--color-muted);margin:5px 0}.glossary strong{color:var(--color-text)}main{position:relative;overflow:hidden;background:var(--color-canvas)}.canvas-tools{position:absolute;z-index:2;top:12px;left:12px}.canvas-tools .readout{height:32px;border:1px solid var(--color-border);border-radius:6px;background:#fff;padding:6px 10px;font-size:13px;color:var(--color-muted)}
svg{width:100%;height:100vh;display:block;background:var(--color-canvas);cursor:grab}.lane-title{font-size:12px;fill:var(--color-muted);font-weight:700;text-transform:uppercase}.domain-title{font-size:14px;fill:var(--color-text);font-weight:700}.edge{stroke:#8fa2ae;stroke-width:1.35;fill:none;opacity:.36}.edge.focused{stroke:var(--color-accent);stroke-width:2.8;opacity:.95}.edge.warn{stroke:var(--color-warning)}.edge.risk{stroke:var(--color-danger)}.edge-label{font-size:11px;fill:var(--color-muted);paint-order:stroke;stroke:var(--color-canvas);stroke-width:4;stroke-linejoin:round}.service-node rect,.trace-step rect,.raw-node rect{fill:#fff;stroke:var(--color-border);stroke-width:1.2;rx:6}.service-node.selected rect,.trace-step.selected rect,.raw-node.selected rect{stroke:var(--color-accent);stroke-width:2.2}.service-node.dim,.trace-step.dim,.raw-node.dim{opacity:.35}.raw-node circle{fill:#fff;stroke:var(--color-border);stroke-width:1.5}.raw-node.focused circle,.raw-node.selected circle{stroke:var(--color-accent);stroke-width:3}.service-title,.trace-title,.raw-title{font-size:13px;font-weight:700;fill:var(--color-text)}.service-meta,.trace-meta,.raw-meta{font-size:11px;fill:var(--color-muted)}.trace-step.frontend_step rect,.trace-step.api_contract rect{fill:#fefcf7}.trace-step.backend_route rect,.trace-step.backend_handler rect,.trace-step.backend_step rect{fill:#f7fbf8}.trace-step.test rect{fill:#f7f8fc}
.trace-step.focused rect,.raw-node.focused rect{stroke:var(--color-accent);stroke-width:3}.issue-card rect{fill:#fff;stroke:var(--color-border);stroke-width:1.2;rx:6}.issue-card.selected rect{stroke:var(--color-accent);stroke-width:2.2}.issue-title{font-size:14px;font-weight:700;fill:var(--color-text)}.issue-meta{font-size:12px;fill:var(--color-muted)}.source-link{color:var(--color-accent);text-decoration:none}.source-link:hover{text-decoration:underline}.empty{color:var(--color-muted);font-size:14px;line-height:1.55}.detail-list{display:grid;gap:11px}.detail-item{border-top:1px solid var(--color-border);padding-top:11px;font-size:14px;line-height:1.42;overflow-wrap:anywhere}.detail-item strong{display:block;font-size:15px;color:var(--color-text);margin-bottom:2px}.detail-item small{display:block;color:var(--color-muted);font-size:13px;line-height:1.35}.relation-section{border-top:1px solid var(--color-border);padding-top:12px;margin-top:12px}.relation-section h3{font-size:16px;margin:0 0 8px}.relation-row{display:block;width:100%;text-align:left;border:1px solid var(--color-border);border-radius:6px;background:#fff;padding:9px;margin:6px 0;cursor:pointer}.relation-row.static{cursor:default}.relation-row strong{font-size:14px}.relation-row span{display:block;color:var(--color-muted);font-size:13px;margin-top:2px;overflow-wrap:anywhere}.relation-row.selected{border-color:var(--color-accent);box-shadow:inset 3px 0 0 var(--color-accent)}.badge{display:inline-block;border:1px solid var(--color-border);border-radius:5px;padding:2px 6px;font-size:12px;color:var(--color-muted);margin:3px 4px 0 0}.badge.ok{color:var(--color-success);border-color:#9ac9ad}.badge.warn{color:var(--color-warning);border-color:#d6b779}.badge.risk{color:var(--color-danger);border-color:#d99b9b}
@media (max-width:1240px){.shell{grid-template-columns:1fr;grid-template-areas:"side" "details" "main"}.side,.details{border:0;border-bottom:1px solid var(--color-border)}.filters button,.modes button,.canvas-tools button{min-height:44px}svg{height:72vh}}
button:focus-visible,input:focus-visible,[data-select-id]:focus-visible{outline:3px solid var(--color-focus);outline-offset:2px}
@media (prefers-reduced-motion:reduce){*{scroll-behavior:auto!important;transition-duration:0.01ms!important;animation-duration:0.01ms!important}}`
